#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.dirname(os.path.realpath(__file__)))
import sliceapi

if "__main__" == __name__:
    if len(sys.argv) < 4:
        sys.exit("Usage: %s <origin> <name> <record type> <data> [ttl]" % sys.argv[0])

    (origin, name, record_type, data) = sys.argv[1:5]

    data = {"name":name, "record_type":record_type, "data":data}
    if len(sys.argv) > 5:
        data["ttl"] = int(sys.argv[5])

    dns = sliceapi.SliceDNS(origin)
    status = dns.update_record(name, data)
    if status:
        sys.exit(0)
    sys.exit(1)
